# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.695089 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.my
# We were before running iteration 6
# finished Sat May 23 08:21:05 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.3/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.3/reordering-table.3.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/lm/myg2p-data.binlm.2 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0255415 0.0370218 0.0580066 -0.17494 0.041044 0.0566767
Distortion0= 0.00564626
LM0= 0.041898
WordPenalty0= 0.049962
PhrasePenalty0= -0.252247
TranslationModel0= 0.18618 -0.0250029 -0.00936042 0.0364729
UnknownWordPenalty0= 1
