# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.695125 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.my
# We were before running iteration 8
# finished Sat May 23 08:23:00 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.3/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.3/reordering-table.3.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/lm/myg2p-data.binlm.2 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0228549 0.0376927 0.0590578 -0.163137 0.0417878 0.0577038
Distortion0= 0.00574858
LM0= 0.0426573
WordPenalty0= 0.0508674
PhrasePenalty0= -0.256818
TranslationModel0= 0.189554 -0.025456 -0.00953005 0.0371339
UnknownWordPenalty0= 1
