# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.777868 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.ph
# We were before running iteration 2
# finished Sat May 23 09:30:06 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.3/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.3/reordering-table.3.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/lm/myg2p-data.binlm.4 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= -0.254897 0.329687 0.0472899 -0.00608179 0.00229618 0.00753633
Distortion0= 0.0687558
LM0= 0.0952017
WordPenalty0= 0.0434779
PhrasePenalty0= 0.00124661
TranslationModel0= 0.0913618 0.0343503 0.01081 0.00700792
UnknownWordPenalty0= 1
