# MERT optimized configuration
# decoder /home/kyalkalay/tools/mosesdecoder/bin/moses
# BLEU 0.692786 on dev /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/dev_clean.my
# We were before running iteration 5
# finished Tue Jun  2 01:14:11 +0630 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_less_pruned/my-ph/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_less_pruned/my-ph/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_less_pruned/my-ph/lm/myph.binlm.1 order=5

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.227816 0.0221568 0.154462 -0.111402 0.036863 0.0198402
Distortion0= 0.012268
LM0= 0.0454611
WordPenalty0= 0.226198
PhrasePenalty0= 0.0203276
TranslationModel0= 0.107841 -0.00417451 0.00613855 -0.00505045
UnknownWordPenalty0= 1
