# MERT optimized configuration
# decoder /home/kyalkalay/tools/mosesdecoder/bin/moses
# BLEU 0.776846 on dev /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/dev_clean.ph
# We were before running iteration 2
# finished Tue Jun  2 01:57:02 +0630 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_phrase11/ph-my/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_phrase11/ph-my/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_phrase11/ph-my/lm/myph.binlm.1 order=5

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0945172 0.00246959 0.0409754 -0.236474 0.102284 0.0396866
Distortion0= 0.0877033
LM0= 0.0893828
WordPenalty0= 0.0725083
PhrasePenalty0= -0.105571
TranslationModel0= 0.088717 0.027946 -0.00563719 0.00612762
UnknownWordPenalty0= 1
