# MERT optimized configuration
# decoder /home/elio/tool/mosesbin/ubuntu-17.04/moses//bin/moses
# BLEU 0.782332 on dev /mnt/data/personal_projects/NandarLinn-SMT-Assignment/clean-data/dev.ph
# We were before running iteration 3
# finished Sun May 31 04:39:02 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/mnt/data/personal_projects/NandarLinn-SMT-Assignment/pbsmt/baseline/ph-my/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/mnt/data/personal_projects/NandarLinn-SMT-Assignment/pbsmt/baseline/ph-my/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/mnt/data/personal_projects/NandarLinn-SMT-Assignment/pbsmt/baseline/ph-my/lm/myrk.binlm.1 order=5

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0273611 0.060216 0.0800408 0.00352241 0.0899669 0.080961
Distortion0= 0.0746584
LM0= 0.109391
WordPenalty0= 0.0535018
PhrasePenalty0= -0.275991
TranslationModel0= 0.0827096 0.0261152 -0.00610718 0.0294571
UnknownWordPenalty0= 1
