# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.772443 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.ph
# We were before running iteration 2
# finished Fri May 22 05:44:59 AM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/lm/myg2p-data.binlm.2 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.113223 0.0194282 0.246267 -0.164763 0.0243003 0.0351837
Distortion0= 0.0164088
LM0= 0.114749
WordPenalty0= 0.0920284
PhrasePenalty0= 0.00450901
TranslationModel0= 0.0562799 0.0748062 0.0232404 -0.0148118
UnknownWordPenalty0= 1
