# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.778035 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.ph
# We were before running iteration 2
# finished Sun May 24 11:11:50 AM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.5/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.5/reordering-table.5.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/lm/myg2p-data.binlm.4 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0278499 0.204827 0.312789 0.0710137 0.0205264 0.0384432
Distortion0= 0.0174066
LM0= 0.0610354
WordPenalty0= 0.0318081
PhrasePenalty0= -0.129238
TranslationModel0= 0.0283232 0.0402294 0.00367849 0.0128315
UnknownWordPenalty0= 1
