# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.78539 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.ph
# We were before running iteration 4
# finished Sat May 23 08:28:57 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.3/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/tuning/filtered.3/reordering-table.3.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/ph-my/lm/myg2p-data.binlm.2 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0457817 0.0190743 0.106357 -0.0808824 0.0417534 0.0240155
Distortion0= 0.041401
LM0= 0.087356
WordPenalty0= -0.175826
PhrasePenalty0= -0.247684
TranslationModel0= 0.0180941 0.0700479 0.0321863 -0.00954039
UnknownWordPenalty0= 1
