# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.689292 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.my
# We were before running iteration 2
# finished Sun May 24 11:04:53 AM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.5/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.5/reordering-table.5.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/lm/myg2p-data.binlm.4 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 7.12461e-05 0.000704402 0.000970956 0.00332383 0.000977545 0.0003275
Distortion0= 0.000737971
LM0= 0.000729161
WordPenalty0= -0.990525
PhrasePenalty0= -0.000147009
TranslationModel0= 0.000805952 0.000264486 0.000103936 0.000311262
UnknownWordPenalty0= 1
