# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.683957 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned/dev.my
# We were before running iteration 2
# finished Thu May 21 04:07:13 AM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline/my-ph/tuning/filtered.2/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline/my-ph/tuning/filtered.2/reordering-table.2.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline/my-ph/lm/myg2p-data.binlm.1 order=5

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.099238 0.0599807 0.0282271 0.0207305 0.0291438 0.0867207
Distortion0= 0.101084
LM0= 0.0773097
WordPenalty0= 0.305245
PhrasePenalty0= 0.0156778
TranslationModel0= 0.141599 -0.00783663 0.0266404 -0.00056635
UnknownWordPenalty0= 1
