# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.68558 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.my
# We were before running iteration 5
# finished Fri May 22 05:42:27 AM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/lm/myg2p-data.binlm.2 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.20999 0.0787821 0.0390794 0.00688204 0.176418 0.0973198
Distortion0= 0.0029959
LM0= 0.0480646
WordPenalty0= 0.157285
PhrasePenalty0= -0.016991
TranslationModel0= 0.108254 -0.0274304 -0.00912721 0.021381
UnknownWordPenalty0= 1
