# MERT optimized configuration
# decoder /home/elio/tool/mosesbin/ubuntu-17.04/moses//bin/moses
# BLEU 0.787207 on dev /mnt/data/personal_projects/NandarLinn-SMT-Assignment/clean-data/dev.ph
# We were before running iteration 3
# finished Sun May 31 05:41:38 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/mnt/data/personal_projects/NandarLinn-SMT-Assignment/pbsmt-normalize/baseline/ph-my/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/mnt/data/personal_projects/NandarLinn-SMT-Assignment/pbsmt-normalize/baseline/ph-my/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/mnt/data/personal_projects/NandarLinn-SMT-Assignment/pbsmt-normalize/baseline/ph-my/lm/myrk.binlm.1 order=5

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0764133 0.0115034 0.10181 -0.114073 0.0675106 0.0178046
Distortion0= 0.0584667
LM0= 0.0857798
WordPenalty0= 0.0410797
PhrasePenalty0= -0.286838
TranslationModel0= 0.0261048 0.0667422 0.0339157 -0.0119578
UnknownWordPenalty0= 1
