# MERT optimized configuration
# decoder /home/kyalkalay/tools/mosesdecoder/bin/moses
# BLEU 0.786795 on dev /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/dev_clean.ph
# We were before running iteration 8
# finished Tue Jun  2 02:11:05 +0630 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_less_pruned/ph-my/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_less_pruned/ph-my/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_original_clean_experiments/pbsmt_5gram_less_pruned/ph-my/lm/myph.binlm.1 order=5

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.0480167 0.148364 0.0529907 0.0240317 0.0693141 0.0868546
Distortion0= 0.0765636
LM0= 0.0663569
WordPenalty0= 0.0527235
PhrasePenalty0= -0.248188
TranslationModel0= 0.0111273 0.0622611 0.0356119 -0.0175961
UnknownWordPenalty0= 1
