# MERT optimized configuration
# decoder /home/kyalkalay/tools/mosesdecoder/bin/moses
# BLEU 0.786812 on dev /media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/g2p-par/dev_clean.ph
# We were before running iteration 4
# finished Sun May 31 19:16:41 +0630 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_3gram/baseline/ph-my/tuning/filtered.1/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_3gram/baseline/ph-my/tuning/filtered.1/reordering-table.1.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/media/kyalkalay/Data/AI-Class/assignment-6_aung_hein/pbsmt_3gram/baseline/ph-my/lm/myph.binlm.1 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.261879 0.0965437 0.0401644 0.0107402 0.00550552 0.0349986
Distortion0= 0.0463048
LM0= 0.0681254
WordPenalty0= 0.0215205
PhrasePenalty0= -0.335838
TranslationModel0= 0.0163361 0.0520156 0.00948377 0.000544985
UnknownWordPenalty0= 1
