# MERT optimized configuration
# decoder /home/lawun330/NLP/ubuntu-17.04/moses/bin/moses
# BLEU 0.689258 on dev /home/lawun330/Desktop/basic-statistical-machine-translation/data/cleaned_2/dev.my
# We were before running iteration 2
# finished Sat May 23 09:26:08 PM +07 2026
### MOSES CONFIG FILE ###
#########################

# input factors
[input-factors]
0

# mapping steps
[mapping]
0 T 0

[distortion-limit]
6

# feature functions
[feature]
UnknownWordPenalty
WordPenalty
PhrasePenalty
PhraseDictionaryMemory name=TranslationModel0 num-features=4 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.3/phrase-table.0-0.1.1.gz input-factor=0 output-factor=0 
LexicalReordering name=LexicalReordering0 num-features=6 type=wbe-msd-bidirectional-fe-allff input-factor=0 output-factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/tuning/filtered.3/reordering-table.3.wbe-msd-bidirectional-fe.0-0.1 
Distortion
KENLM name=LM0 factor=0 path=/home/lawun330/Desktop/basic-statistical-machine-translation/baseline2/my-ph/lm/myg2p-data.binlm.4 order=3

# dense weights for feature functions

[v]
0
[weight]

LexicalReordering0= 0.313284 0.12126 0.00623699 0.00548424 0.0492494 0.0560727
Distortion0= 0.0630066
LM0= 0.0553724
WordPenalty0= 0.196208
PhrasePenalty0= -0.0317178
TranslationModel0= 0.0661477 0.0175127 0.0172206 -0.00122686
UnknownWordPenalty0= 1
